name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo greetings and commit SHA
      run: |
        echo Hello Github Action
        echo Commit SHA: ${{ github.sha }}
